#!/usr/bin/env bash
USAGE="$(cat <<EOF
\e[1;40;39m Usage: tepuknyamuk (stop|start|status) [SERVICE|APPGROUP]\e[0m.
Please specify a command to manage the tepuk-nyamuk app. 
Commands:
stop : stop all services pertaining to the app.
start: start all services pertaining to the app.
status: list services and whether they are up or down.

----SERVICES----:
>> (individual service instances)  <<
redis
postgresql
gms (node)
appcs (node)
nginx
datadog-agent

---APPGROUP---- NOT IMPLEMENTED YET.
>> (A group of service instances that comprise an app service.)  <<
gmsapp (comprises of gms service and redis)
appcsapp (comprises of appcs service and postgresql)
web (nginx)


----NOTE----:
PID files are located in ~/.tepuknyamuk for the services who need to store PID files.
EOF
)";
TITLE='\e[1;44;97mtepuknyamuk cli tool.\e[0m '
if [[ "$(uname -s)" == "Darwin" ]]; 
then echo -e "\e[1;41;97m Must be in ubuntu environment to launch tepuknyamuk live. Sorry!"
    exit 1;
fi

if [[ $# -lt 1 ]] || [[ $1 == '--help' ]] || [[ $1 == '-h' ]]; 
then echo -e "$TITLE";
 echo -e "$USAGE";
else
# start command
if [[ $1 == 'start' ]]; then
	case "$2" in 
		(redis)
		echo -e "\e[0;40;34m starting redis...\e[0m";
		redis-server ~/.tepuknyamuk/redis-daemon.conf && echo -e '\e[32m >>>> redis-server daemon running\e[0m'
		;;
		(postgresql)
		echo -e "\e[0;40;34m starting postgresql...\e[0m";
		sudo systemctl start postgresql && echo -e '\e[32m >>>> postgresql running .\e[0m'
		;;
		(gms)
		echo -e "\e[0;40;34m starting gms node service...\e[0m";
		forever start --pidFile ~/.tepuknyamuk/gms-daemon.pid ~/projects/tepuk-nyamuk/gameMarshallingService/gmsapp.js production.host && echo -e '\e[32m >>>> gms daemon running..' 
		;;
		(appcs)
		echo -e "\e[0;40;34m starting appcs node service...\e[0m";
		forever start --pidFile ~/.tepuknyamuk/appcs-daemon.pid ~/projects/tepuk-nyamuk/appCentralService/appcsapp.js production.host && echo -e '\e[32m >>>> appcs daemon running...'  
		;;
		(nginx)
		echo -e "\e[0;40;34m starting nginx service...\e[0m";
		sudo systemctl start nginx && echo -e '\e[32m >>>> nginx web server running....' 
		;;
        (datadog-agent)
		echo -e "\e[0;40;34m starting datadog agent....\e[0m";
            sudo systemctl start datadog-agent && echo -e "\e[32m >>>> datadog-agent running .....\e[0m"
            ;;
		(*)
         if [[ $#  -lt 2 ]]; then

		echo -e "\e[0;40;34m starting services...\e[0m";
		SERVICES=0
		redis-server ~/.tepuknyamuk/redis-daemon.conf && echo -e '\e[32m >>>> redis-server daemon running\e[0m' && (( SERVICES+=1 ));
		sudo systemctl start postgresql && echo -e '\e[32m >>>> postgresql running .\e[0m'  && (( SERVICES+=1 ));
		forever start --pidFile ~/.tepuknyamuk/gms-daemon.pid ~/projects/tepuk-nyamuk/gameMarshallingService/gmsapp.js production.host && echo -e '\e[32m >>>> gms daemon running..'  && (( SERVICES+=1 ));
		forever start --pidFile ~/.tepuknyamuk/appcs-daemon.pid ~/projects/tepuk-nyamuk/appCentralService/appcsapp.js production.host && echo -e '\e[32m >>>> appcs daemon running...'  && (( SERVICES+=1 ));
		sudo systemctl start nginx && echo -e '\e[32m >>>> nginx web server running....\e[0m'  && (( SERVICES+=1 ));
		echo -e "\e[0;40;34m starting datadog agent....\e[0m";
        sudo systemctl start datadog-agent   && echo -e "\e[32m >>>> datadog-agent running .....\e[0m" && (( SERVICES += 1));

		echo -e "\e[36m [ $SERVICES/6 services up and running.].\e[0m"

    else
        echo -e "\e[1;41;97m Unknown service \"$2\" to start.\e[0m"
        exit 1;
    fi
        ;;
		esac

# stop command
else if [[ $1 == 'stop' ]]; 
then
	case "$2" in 
		(redis)
		echo -e "\e[0;40;34m stopping redis...\e[0m";
	[[ -a ~/.tepuknyamuk/redis-server-daemon.pid ]] && (sudo kill $(cat ~/.tepuknyamuk/redis-server-daemon.pid) && echo -e '\e[32m >>>> killed redis-server daemon' ) || echo -e '\e[31m ERROR. NO redis server pid file found. \e[0m';
		;;
		(postgresql)
		echo -e "\e[0;40;34m stopping postgresql...\e[0m";
	sudo systemctl stop postgresql && echo -e '\e[32m >>>> stopped postgresql.' 
		;;
    (appcs)
		echo -e "\e[0;40;34m stopping appcs node service...\e[0m";
        [[ -a ~/.tepuknyamuk/appcs-daemon.pid ]] &&  (forever stop $(cat ~/.tepuknyamuk/appcs-daemon.pid) && echo -e '\e[32m >>>> stopped appcs daemon...') || echo -e "\e[31m ERROR. No appcs pid file found. \e[0m"
        ;;
		(gms)
		echo -e "\e[0;40;34m stopping gms node service...\e[0m";
        [[ -a ~/.tepuknyamuk/gms-daemon.pid ]] && (forever stop $( cat ~/.tepuknyamuk/gms-daemon.pid)  && echo -e '\e[32m >>>> stopped gms daemon...')  || echo -e "\e[31m Error. No gms pid file found. \e[0m"
    ;;
		(nginx)
		echo -e "\e[0;40;34m stopping nginx service...\e[0m";
	sudo systemctl stop nginx && echo -e '\e[32m >>>> stopped nginx web server....' 
		;;
        (datadog-agent)
		echo -e "\e[0;40;34m stopping datadog agent....\e[0m";
            sudo systemctl stop datadog-agent
            ;;
		(*)
            if [[ $# -lt 2 ]]; then
	echo -e "\e[0;40;34m stopping services...\e[0m";
	[[ -a ~/.tepuknyamuk/redis-server-daemon.pid ]] && (sudo kill $(cat ~/.tepuknyamuk/redis-server-daemon.pid) && echo -e '\e[32m >>>> killed redis-server daemon' ) || echo -e '\e[31m ERROR. NO redis server pid file found. \e[0m';
	sudo systemctl stop postgresql && echo -e '\e[32m >>>> stopped postgresql.' 
	forever stopall  && echo -e '\e[32m >>>> stopped appcs daemon...'  &&  echo -e '\e[32m >>>> stopped gms daemon...' 
	sudo systemctl stop nginx && echo -e '\e[32m >>>> stopped nginx web server....' 
    echo -e "\e[0m Datadog-agent isn\'t stopped, due to continuous monitoring reasons. Stop using tpk stop datadog-agent if needed."
else
echo -e "\e[1;41;97m Unknown service \"$2\" to stop. \e[0m"
fi
        ;;
    esac
	

# status command
else if [[ $1 == 'status' ]]; then
	echo -e "\e[0;40;34m status...\e[0m";
	echo -e "\e[1;40;37m Running node appservices:\e[0m" | toilet -f term -F border;
	forever list;
	echo -e "\e[1;40;37m Redis @ 6379 ping: \e[0m" | toilet -f term -F border;
	redis-cli ping > /dev/null 2>&1 && REDISSTATUS="PONG" || REDISSTATUS="DOWN";
	if [[ $REDISSTATUS == 'PONG' ]];
	then
		echo -e "\e[36m[PONG] \e[0m"  
	else
		echo -e "\e[1;40;31mDown.\e[0m";
	fi
	echo -e "\e[1;40;37m Postgresql status: \e[0m"| toilet -f term -F border;
	systemctl -n 0 status postgresql |cat;
	echo -e "\e[1;40;37m Nginx status: \e[0m"| toilet -f term -F border;
	systemctl -n 0 status nginx |cat ;
	echo -e "\e[1;40;37m Datadog-agent status: \e[0m"| toilet -f term -F border;
	systemctl -n 0 status datadog-agent|cat ;
	else
		echo -e "\e[1;101;97mUnrecognized command $1.\e[0m"
		echo -e "$TITLE"
	echo -e "$USAGE";

fi
fi
fi

fi
